const quotes = {
    motivational: [
        "Believe you can and you're halfway there.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The only limit to our realization of tomorrow is our doubts of today.",
        "Dream big and dare to fail.",
        "Act as if what you do makes a difference. It does.",
        "The only way to do great work is to love what you do.",
        "Don’t watch the clock; do what it does. Keep going.",
        "Your limitation—it's only your imagination.",
        "Push yourself, because no one else is going to do it for you.",
        "Great things never come from comfort zones.",
        "Dream it. Wish it. Do it.",
        "Success doesn’t just find you. You have to go out and get it.",
        "The harder you work for something, the greater you’ll feel when you achieve it.",
        "Dream bigger. Do bigger.",
        "Don’t stop when you’re tired. Stop when you’re done.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Do something today that your future self will thank you for.",
        "Little things make big days.",
        "It’s going to be hard, but hard does not mean impossible.",
        "Don’t wait for opportunity. Create it.",
        "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
        "The key to success is to focus on goals, not obstacles.",
        "Dream it. Believe it. Build it.",
        "You are never too old to set another goal or to dream a new dream.",
        "Success usually comes to those who are too busy to be looking for it.",
        "Keep going. Everything you need will come to you at the perfect time.",
        "Failure will never overtake me if my determination to succeed is strong enough.",
        "Don’t wish it were easier. Wish you were better.",
        "It always seems impossible until it’s done.",
        "Opportunities don’t happen. You create them.",
        "Dream as if you'll live forever, live as if you'll die today.",
        "I find that the harder I work, the more luck I seem to have.",
        "Try not to become a person of success, but rather try to become a person of value.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "Our greatest glory is not in never falling, but in rising every time we fall.",
        "The way to get started is to quit talking and begin doing.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "Do not wait to strike till the iron is hot; but make it hot by striking.",
        "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
        "The best revenge is massive success.",
        "I attribute my success to this: I never gave or took any excuse.",
        "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
        "The only place where success comes before work is in the dictionary.",
        "Do not be embarrassed by your failures, learn from them and start again.",
        "It does not matter how slowly you go as long as you do not stop.",
        "The best time to plant a tree was 20 years ago. The second best time is now.",
        "Only put off until tomorrow what you are willing to die having left undone.",
        "We may encounter many defeats but we must not be defeated.",
        "It's not whether you get knocked down; it's whether you get up.",
        "I failed my way to success.",
        "If you are not willing to risk the usual, you will have to settle for the ordinary."
    ],

    funny: [
        "I'm on a whiskey diet. I've lost three days already.",
        "I'm not arguing, I'm just explaining why I'm right.",
        "I used to think I was indecisive, but now I'm not too sure.",
        "I'm not lazy, I'm just very relaxed.",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "If I agreed with you, we’d both be wrong.",
        "I always wanted to be somebody, but now I realize I should have been more specific.",
        "I'm writing a book. I've got the page numbers done.",
        "I'm on a seafood diet. I see food, and I eat it.",
        "I didn't fall, I'm just spending some quality time with the floor.",
        "I’m reading a book on anti-gravity. It’s impossible to put down.",
        "I would lose weight, but I hate losing.",
        "When life gives you lemons, squirt someone in the eye.",
        "I’m not running late, I just have my own time zone.",
        "The only thing I'm committed to right now is staying comfortable.",
        "Exercise? I thought you said extra fries.",
        "My bed is a magical place where I suddenly remember everything I forgot to do.",
        "My boss told me to have a good day. So I went home.",
        "I'm not arguing, I'm just explaining why I'm right.",
        "Of course I talk to myself; sometimes I need expert advice.",
        "I'd agree with you but then we'd both be wrong.",
        "I am on a seafood diet. I see food and I eat it.",
        "I'm so good at sleeping I can do it with my eyes closed.",
        "I'm not superstitious, but I am a little stitious.",
        "If you think nobody cares, try missing a couple of payments.",
        "My therapist says I have a preoccupation with vengeance. We'll see about that.",
        "Money can't buy happiness, but it can buy ice cream, which is pretty much the same thing.",
        "If at first you don't succeed, then skydiving definitely isn't for you.",
        "If you think education is expensive, try ignorance.",
        "I finally got 8 hours of sleep. It took me 4 days, but whatever.",
        "I'm not great at advice. Can I interest you in a sarcastic comment?",
        "I'm in shape. Unfortunately, that shape is a potato.",
        "I don't need a hair stylist, my pillow gives me a new hairstyle every morning.",
        "The future is shaped by your dreams, so stop wasting time and go to sleep!",
        "I have not lost my mind - it's backed up on a disk somewhere.",
        "I don’t trip, I do random gravity checks.",
        "Sometimes I shock myself with how smart I am. Other times I try to get out of the car with my seatbelt on.",
        "I'm not arguing. I'm simply explaining why I'm right.",
        "Do I run? Yes. Out of time, patience, and money.",
        "Why did I walk into this room? Am I lost, or did I just want snacks?",
        "If Cinderella’s shoe fit perfectly, why did it fall off?",
        "I’d like to help you out. Which way did you come in?",
        "Common sense is like deodorant. The people who need it most never use it.",
        "Some people are like clouds. When they disappear, it's a beautiful day.",
        "Sometimes I wonder if I’m too picky, but then I watch my dog try to find a place to poop.",
        "If you’re hotter than me, that means I’m cooler than you.",
        "I'm on a new diet. I call it the 'I can't afford food' diet.",
        "I didn’t want to believe my dad was stealing from his job as a traffic cop, but when I got home, all the signs were there."
    ],

    useless: [
        "A shrimp’s heart is in its head.",
        "Bananas are berries, but strawberries aren’t.",
        "Humans share 50% of their DNA with bananas.",
        "Honey never spoils. Archaeologists have found pots of it in ancient tombs.",
        "There are more trees on Earth than stars in the Milky Way.",
        "The inventor of the Pringles can is now buried in one.",
        "Octopuses have three hearts.",
        "A jiffy is an actual unit of time. It’s 1/100th of a second.",
        "Scotland’s national animal is the unicorn.",
        "It’s impossible to hum while holding your nose.",
        "An apple, potato, and onion all taste the same when you eat them with your nose plugged.",
        "Banging your head against a wall burns 150 calories an hour.",
        "Some cats are allergic to humans.",
        "Kangaroos can’t walk backward.",
        "Sloths only poop once a week.",
        "A group of flamingos is called a ‘flamboyance.’",
        "The shortest war in history lasted 38 to 45 minutes.",
        "There is a basketball court on the top floor of the U.S. Supreme Court Building.",
        "Sea cucumbers eat with their feet.",
        "You can't fold a piece of paper more than 7 times.",
        "The inventor of the frisbee was turned into a frisbee after he died.",
        "Cows have best friends and get stressed when they are separated.",
        "Cleopatra lived closer to the invention of the iPhone than to the construction of the Great Pyramid.",
        "Turtles can breathe through their butts.",
        "A snail can sleep for three years.",
        "The Twitter bird has a name: Larry.",
        "The average person will spend six months of their life waiting for red lights to turn green.",
        "Polar bears have black skin under their white fur.",
        "A jiffy is 1/100th of a second.",
        "Most toilet paper in France is pink.",
        "A duel between three people is actually called a truel.",
        "A blue whale’s heart weighs as much as a small car.",
        "Mosquitoes are the deadliest animals in the world.",
        "Humans are the only animals that blush.",
        "Your bones are four times stronger than concrete.",
        "The human nose can remember 50,000 different scents.",
        "Bees sometimes sting other bees.",
        "Dogs’ nose prints are unique, similar to human fingerprints.",
        "The dot over the letter ‘i’ is called a tittle.",
        "The Eiffel Tower can be 15 cm taller during the summer.",
        "An ostrich’s eye is bigger than its brain.",
        "The first oranges weren’t orange.",
        "One light year is about 5.88 trillion miles.",
        "There is a species of jellyfish that is immortal.",
        "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
        "The word “nerd” was first coined by Dr. Seuss.",
        "Giraffes have no vocal cords.",
        "Snails have 14,000 teeth and some can even kill you.",
        "Sharks are older than trees.",
        "A day on Venus is longer than a year on Venus."
    ]
};


function generateQuote(category) {
    const categoryQuotes = quotes[category];
    const randomIndex = Math.floor(Math.random() * categoryQuotes.length);
    document.getElementById('quote-display').textContent = categoryQuotes[randomIndex];
}